import { Injectable } from '@nestjs/common';
import { Session } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';

@Injectable()
export class SessionService {
  constructor(private readonly prisma: PrismaService) {}

  /**
   * Create a new session for a user.
   * tokenFamily is auto-generated by the database (UUID default).
   */
  async create(data: {
    userId: string;
    refreshTokenHash: string;
    userAgent?: string;
    ipAddress?: string;
    expiresAt: Date;
  }): Promise<Session> {
    return this.prisma.session.create({ data });
  }

  /**
   * Find a session by its refresh token hash (used during refresh token rotation).
   */
  async findByRefreshTokenHash(hash: string): Promise<Session | null> {
    return this.prisma.session.findFirst({
      where: { refreshTokenHash: hash },
    });
  }

  /**
   * Find a session by its unique token family (used during refresh token rotation).
   */
  async findByTokenFamily(tokenFamily: string): Promise<Session | null> {
    return this.prisma.session.findUnique({ where: { tokenFamily } });
  }

  /**
   * Find a session by its ID.
   */
  async findById(id: string): Promise<Session | null> {
    return this.prisma.session.findUnique({ where: { id } });
  }

  /**
   * Update refresh token hash and lastUsedAt for token rotation.
   */
  async rotateToken(sessionId: string, newHash: string): Promise<void> {
    await this.prisma.session.update({
      where: { id: sessionId },
      data: { refreshTokenHash: newHash, lastUsedAt: new Date() },
    });
  }

  /**
   * List active (non-revoked, non-expired) sessions for a user.
   * Ordered by most recent first.
   */
  async listActive(userId: string): Promise<Session[]> {
    return this.prisma.session.findMany({
      where: {
        userId,
        isRevoked: false,
        expiresAt: { gt: new Date() },
      },
      orderBy: { createdAt: 'desc' },
    });
  }

  /**
   * Revoke a single session by ID.
   */
  async revoke(sessionId: string): Promise<void> {
    await this.prisma.session.update({
      where: { id: sessionId },
      data: { isRevoked: true },
    });
  }

  /**
   * Revoke all sessions for a user EXCEPT the specified session.
   * Used when changing password or logging out all other devices.
   */
  async revokeAllExcept(userId: string, exceptSessionId: string): Promise<void> {
    await this.prisma.session.updateMany({
      where: {
        userId,
        id: { not: exceptSessionId },
        isRevoked: false,
      },
      data: { isRevoked: true },
    });
  }

  /**
   * Revoke all sessions in a token family (for refresh token reuse detection).
   */
  async revokeByTokenFamily(tokenFamily: string): Promise<void> {
    await this.prisma.session.updateMany({
      where: { tokenFamily, isRevoked: false },
      data: { isRevoked: true },
    });
  }

  /**
   * Revoke ALL sessions for a user (used on password reset, force-reset).
   */
  async revokeAll(userId: string): Promise<void> {
    await this.prisma.session.updateMany({
      where: { userId, isRevoked: false },
      data: { isRevoked: true },
    });
  }
}
