ALTER TYPE "CancellationReason" ADD VALUE IF NOT EXISTS 'PROCON';
ALTER TYPE "CancellationReason" ADD VALUE IF NOT EXISTS 'RECLAME_AQUI';
ALTER TYPE "CancellationReason" ADD VALUE IF NOT EXISTS 'EMAIL_REQUEST';
